worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # 负载均衡配置，分发到两个不同的后端实例
    upstream backend_api {
        # 轮询 (默认)
        server app1:8081;
        server app2:8082;
        
        # 测试其他负载均衡算法可以解开下面的注释
        # least_conn; # 最少连接数
        # ip_hash;    # 基于 IP 的 Hash
    }

    server {
        listen       80;
        server_name  localhost;

        # 动静分离 - 静态资源请求
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            
            # 缓存静态文件
            expires 1h;
            add_header Cache-Control "public";
        }

        # 动静分离 - 动态 API 请求转发到后端
        location /api/ {
            proxy_pass http://backend_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            add_header X-Served-By $upstream_addr always;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}
