-- 延迟 10 秒以确保主库已经初始化完成
SELECT SLEEP(10);

-- 配置主库连接
CHANGE REPLICATION SOURCE TO
  SOURCE_HOST='mysql-master',
  SOURCE_USER='repl',
  SOURCE_PASSWORD='repl_password',
  SOURCE_AUTO_POSITION=1,
  GET_SOURCE_PUBLIC_KEY=1;

-- 启动同步
START REPLICA;
